[server]
enableCORS = false
enableXsrfProtection = false
port = 8502
headless = true


[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#1E90FF"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
